import {
  // Common
  Home,
  Search,
  Settings,
  User,
  Users,
  LogOut,
  LogIn,
  Menu,
  X,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  Plus,
  Minus,
  Close,
  Check,
  AlertCircle,
  Info,
  HelpCircle,
  MoreHorizontal,
  MoreVertical,
  ExternalLink,
  Link,
  Copy,
  Download,
  Upload,
  Save,
  Trash2,
  Edit,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Key,
  Mail,
  Phone,
  Calendar,
  Clock,
  Globe,
  MapPin,
  Flag,
  Star,
  Heart,
  Share2,
  Send,
  RefreshCw,
  Loader2,
  // Editor
  Type,
  Palette,
  Layout,
  Play,
  Pause,
  SkipForward,
  SkipBack,
  Volume2,
  VolumeX,
  Maximize,
  Minimize,
  ZoomIn,
  ZoomOut,
  Move,
  Grid,
  List,
  // Data
  Database,
  Server,
  Cloud,
  Folder,
  File,
  FileText,
  FileImage,
  FileVideo,
  FileAudio,
  FileCode,
  // Media
  Image,
  Video,
  Music,
  Mic,
  Camera,
  // Actions
  PlusCircle,
  MinusCircle,
  XCircle,
  CheckCircle,
  AlertTriangle,
  // Arrows
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowDownRight,
  // Brand
  Github,
  Twitter,
  Linkedin,
  Youtube,
  Instagram,
  Facebook,
} from 'lucide-react'

export const Icons = {
  common: {
    home: Home,
    search: Search,
    settings: Settings,
    user: User,
    users: Users,
    logout: LogOut,
    login: LogIn,
    menu: Menu,
    close: X,
    chevronDown: ChevronDown,
    chevronRight: ChevronRight,
    chevronLeft: ChevronLeft,
    chevronUp: ChevronUp,
    plus: Plus,
    minus: Minus,
    check: Check,
    alert: AlertCircle,
    info: Info,
    help: HelpCircle,
    moreHorizontal: MoreHorizontal,
    moreVertical: MoreVertical,
    external: ExternalLink,
    link: Link,
    copy: Copy,
    download: Download,
    upload: Upload,
    save: Save,
    trash: Trash2,
    edit: Edit,
    eye: Eye,
    eyeOff: EyeOff,
    lock: Lock,
    unlock: Unlock,
    key: Key,
    mail: Mail,
    phone: Phone,
    calendar: Calendar,
    clock: Clock,
    globe: Globe,
    map: MapPin,
    flag: Flag,
    star: Star,
    heart: Heart,
    share: Share2,
    send: Send,
    refresh: RefreshCw,
    loader: Loader2,
  },
  editor: {
    type: Type,
    palette: Palette,
    layout: Layout,
    play: Play,
    pause: Pause,
    skipForward: SkipForward,
    skipBack: SkipBack,
    volume: Volume2,
    volumeX: VolumeX,
    maximize: Maximize,
    minimize: Minimize,
    zoomIn: ZoomIn,
    zoomOut: ZoomOut,
    move: Move,
    grid: Grid,
    list: List,
  },
  data: {
    database: Database,
    server: Server,
    cloud: Cloud,
    folder: Folder,
    file: File,
    fileText: FileText,
    fileImage: FileImage,
    fileVideo: FileVideo,
    fileAudio: FileAudio,
    fileCode: FileCode,
  },
  media: {
    image: Image,
    video: Video,
    music: Music,
    mic: Mic,
    camera: Camera,
  },
  actions: {
    plusCircle: PlusCircle,
    minusCircle: MinusCircle,
    xCircle: XCircle,
    checkCircle: CheckCircle,
    alertTriangle: AlertTriangle,
  },
  arrows: {
    up: ArrowUp,
    down: ArrowDown,
    left: ArrowLeft,
    right: ArrowRight,
    upRight: ArrowUpRight,
    downRight: ArrowDownRight,
  },
  social: {
    github: Github,
    twitter: Twitter,
    linkedin: Linkedin,
    youtube: Youtube,
    instagram: Instagram,
    facebook: Facebook,
  },
}

export type IconName = keyof typeof Icons.common | keyof typeof Icons.editor